service: api-catalog

plugins:
  - serverless-offline
  - serverless-plugin-optimize

custom:
  optimize:
    externalPaths:
      swagger-ui-dist: 'node_modules/swagger-ui-dist'
    external: ['swagger-ui-dist']
  productsTable:
    name: ${self:provider.stage}-products
    arn: !GetAtt productsTable.Arn

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:
    PRODUCTS_TABLE_NAME: ${self:provider.stage}-products
  iamRoleStatements: ${file(./iam/productsTableIAM.yml)}

resources:
  Resources:
    productsTable: ${file(./resources/productsTable.yml):productsTable}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}
